version: "2"

languages:
  JavaScript: true
  TypeScript: true

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50

plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
        typescript:
          mass_threshold: 50

exclude_patterns:
  - "node_modules/"
  - "dist/"
  - "coverage/"
  - "public/"
  - "vendor/"
  - "*.test.ts"
  - "*.spec.ts"
  - "*.test.js"
  - "*.spec.js"
